# Generated by Django 5.0.6 on 2025-09-30 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0004_user_birthday_user_budget_max_user_budget_min_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="user",
            name="budget_max",
        ),
        migrations.RemoveField(
            model_name="user",
            name="budget_min",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hobbies",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_dive_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_activities",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_atmosphere",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_depth_range",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_diving",
        ),
        migrations.RemoveField(
            model_name="user",
            name="residence",
        ),
    ]
