# Generated by Django 5.0.6 on 2025-07-22 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0002_myskills_skillset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillset",
            name="myskills",
        ),
        migrations.AddField(
            model_name="skillset",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skillset",
            name="skill",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="MySkills",
        ),
    ]
