# Generated by Django 5.0.6 on 2025-09-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0007_alter_bucketlist_user_alter_skillset_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("residence", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "preferred_depth_range",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hobbies", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferred_activities",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_atmosphere",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_dive_date", models.DateField(blank=True, null=True)),
                (
                    "preferred_diving",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
