# Generated by Django 5.0.6 on 2025-11-02 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0008_preferences"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preferences",
        ),
    ]
