# Generated by Django 5.0.6 on 2025-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="budget_max",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="budget_min",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
