# Generated by Django 5.0.6 on 2025-09-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wordpresstoken",
            unique_together={("user",)},
        ),
        migrations.AddField(
            model_name="wordpresstoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wordpresstoken",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="wordpresstoken",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordpresstoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="wordpresstoken",
            name="expires_at",
        ),
    ]
