# Generated by Django 5.0.6 on 2025-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0002_alter_wordpresstoken_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordpresstoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
