# Generated by Django 5.0.6 on 2025-11-07 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0003_wordpresstoken_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wordpresstoken",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wordpresstoken",
            name="site_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="wordpresstoken",
            unique_together={("user", "site_id")},
        ),
    ]
