License_Choices = (
    ('PADI Scuba Diver','PADI Scuba Diver'),
    ('PADI Open Water Diver', 'PADI Open Water Diver'),
    ('PADI Advanced Open Water Diver', 'PADI Advanced Open Water Diver'),
    ('PADI Adventure Diver', 'PADI Adventure Diver'),
    ('PADI Rescue Diver', 'PADI Rescue Diver'),
    ('Emergency First Response (EFR)', 'Emergency First Response (EFR)'),
    ('PADI Master Scuba Diver', 'PADI Master Scuba Diver'),
    ('Deep Diver', 'Deep Diver'),
    ('Night Diver', 'Night Diver'),
    ('Wreck Diver', 'Wreck Diver'),
    ('Underwater Navigation', 'Underwater Navigation'),
    ('Peak Performance Buoyancy', 'Peak Performance Buoyancy'),
    ('Enriched Air Diver (Nitrox)', 'Enriched Air Diver (Nitrox)'),
    ('Dry Suit Diver', 'Dry Suit Diver'),
    ('Search and Recovery Diver', 'Search and Recovery Diver'),
    ('Drift Diver', 'Drift Diver'),
    ('Altitude Diver', 'Altitude Diver'),
    ('Boat Diver', 'Boat Diver'),
    ('Sidemount Diver', 'Sidemount Diver'),
    ('Digital Underwater Photographer', 'Digital Underwater Photographer'),
    ('Underwater Naturalist', 'Underwater Naturalist'),
    ('Multilevel Diver', 'Multilevel Diver'),
    ('Fish Identification', 'Fish Identification'),
    ('Ice Diver', 'Ice Diver'),
    ('Cavern Diver', 'Cavern Diver'),
    ('Self-Reliant Diver (for experienced divers)', 'Self-Reliant Diver (for experienced divers)'),
    ('PADI Divemaster', 'PADI Divemaster'),
    ('PADI Assistant Instructor', 'PADI Assistant Instructor'),
    ('PADI Open Water Scuba Instructor (OWSI)', 'PADI Open Water Scuba Instructor (OWSI)'),
    ('PADI Specialty Instructor', 'PADI Specialty Instructor'),
    ('PADI Master Scuba Diver Trainer (MSDT)', 'PADI Master Scuba Diver Trainer (MSDT)'),
    ('PADI IDC Staff Instructor', 'PADI IDC Staff Instructor'),
    ('PADI Master Instructor', 'PADI Master Instructor'),
    ('PADI Course Director', 'PADI Course Director'),
    ('Tec 40', 'Tec 40'),
    ('Tec 45', 'Tec 45'),
    ('Tec 50', 'Tec 50'),
    ('Tec Trimix 65', 'Tec Trimix 65'),
    ('Tec Trimix Diver', 'Tec Trimix Diver'),
    ('Tec Sidemount Diver', 'Tec Sidemount Diver'),
    ('Tec Gas Blender', 'Tec Gas Blender'),
    ('PADI Rebreather Diver', 'PADI Rebreather Diver'),
    ('Advanced Rebreather Diver', 'Advanced Rebreather Diver')
)
