# Generated by Django 5.0.6 on 2025-07-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiveCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Logbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dive_image",
                    models.ImageField(blank=True, null=True, upload_to="logbooks"),
                ),
                ("feeling", models.TextField(blank=True, null=True)),
                ("dive_title", models.CharField(max_length=256)),
                ("dive_site", models.CharField(max_length=256)),
                ("dive_date", models.DateField()),
                ("max_depth", models.FloatField(blank=True, null=True)),
                ("bottom_time", models.DurationField(help_text="예: 00:35:00 (35분)")),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type_of_dive",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fun", "Fun Dive"),
                            ("training", "Training"),
                            ("night", "Night Dive"),
                            ("deep", "Deep Dive"),
                            ("wreck", "Wreck Dive"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(help_text="사용한 납 무게 (kg)")),
                ("start_pressure", models.PositiveSmallIntegerField()),
                ("end_pressure", models.PositiveSmallIntegerField()),
                (
                    "buddy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_logbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dive_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logbook.divecenter",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True, related_name="equipment", to="logbook.equipment"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_logbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-dive_date"],
            },
        ),
    ]
