# Generated by Django 5.0.6 on 2025-11-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logbook",
            name="dive_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
