# Generated by Django 5.0.6 on 2025-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0001_initial"),
    ]

    operations = []
