# Generated by Django 5.0.6 on 2025-07-04 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0002_auto_20250704_0918"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbook",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_logbooks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
