# Generated by Django 5.0.6 on 2025-07-20 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
    ]
