# Generated by Django 5.0.6 on 2025-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0002_logbook_dive_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbook",
            name="dive_image_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
