# Generated by Django 5.0.6 on 2025-07-20 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0003_rename_user_comment_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
    ]
