# Generated by Django 5.0.6 on 2025-09-04 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0004_rename_comment_comment_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logbook",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_logs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
