# Generated by Django 5.0.6 on 2025-09-05 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0005_logbook_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbook",
            name="liked_by",
        ),
    ]
