# Generated by Django 5.0.6 on 2025-09-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0006_remove_logbook_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="logbook",
            name="buddy_str",
            field=models.TextField(blank=True, null=True),
        ),
    ]
