# Generated by Django 5.0.6 on 2025-09-05 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0007_logbook_buddy_str"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbook",
            name="buddy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buddy_logbooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
