# Generated by Django 5.0.6 on 2025-09-05 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0008_alter_logbook_buddy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbook",
            name="equipment",
        ),
    ]
