# Generated by Django 5.0.6 on 2025-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0009_remove_logbook_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="logbook",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, related_name="equipment", to="logbook.equipment"
            ),
        ),
    ]
