# Generated by Django 5.0.6 on 2025-09-05 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0010_logbook_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbook",
            name="buddy_str",
        ),
    ]
