# Generated by Django 5.0.6 on 2025-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="classified_as",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
