# Generated by Django 5.0.6 on 2025-11-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0002_photo_classified_as_alter_photo_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="classified_as",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
